### ISSUE TITLE
need more information how to run this plugin

### ISSUE THREAD

**Issue by dnbhatt1991** [chiabre/jmeter_prom_exporter#2]
hello
![image](https://user-images.githubusercontent.com/17254561/113860351-8c1c1680-97c3-11eb-962d-7a6aa091529c.png)
i have setup the prometheus in docker container .. and face issue like connection refused ..

i am new in docker..
i have build this image and try to export 9270 metrics.
docker run --rm --name jmeter -i -v ${PWD}:${PWD} -w ${PWD} -p 9270:9270 chiabre/jmeter_prom_exporter:5.4-1.6.0 -t [YOUR_SCRIPT].jmx

but  what is pwd .. should i mention the path ?
can you give some clear example ?

Thnaks,

**Comment by chiabre** [comment]
Hi,
first of all to be able to run the img you'll need to add and configure the
prometheus exporter within your test plan (here additional info
https://github.com/johrstrom/jmeter-prometheus-plugin). To ensure that the
exporter is working, launch the test plan and check if the metrics are
available on port 9270 of the machine where the test is running

Once verified that the test plan is ok you can move to the docker image
set-up, To run and expose the data to prometheus you will need the
following info:

   - name of the test plan file --> let's call it TEST_PLAN
   - path of the test plan file --> let's call it TEST_PATH

eg. /home/ubuntu/jmeter/test.jmx:

   - TEST_PLAN =  test.jmx
   - TEST_PATH =  /home/ubuntu/jmeter

to run the test:

docker run --rm --name jmeter -i -v [TEST_PLAN]:/tmp -p 9270:9270
chiabre/jmeter_prom_exporter -t [TEST_PLAN].jmx

eg. /home/ubuntu/jmeter/test.jmx:

docker run --rm --name jmeter -i -v /home/ubuntu/jmeter:/tmp -p 9270:9270
chiabre/jmeter_prom_exporter -t test.jmx

Again, to ensure that the exporter is working, check if the metrics are
available on port 9270 of the machine where the test is running.

Hopefully this helps

Luca

Il giorno mer 7 apr 2021 alle ore 13:40 dnbhatt1991 <
***@***.***> ha scritto:

**Comment by dnbhatt1991** [comment]
thanks , for detail information ...
just one thing to ask .. i am running docker on windows ..  my  jmx file in c:\jmetertest folder .. so i am running below command

docker run --rm --name jmeter -i -v  c:\jmetertest:/tmp -p 9270:9270
chiabre/jmeter_prom_exporter -t test.jmx

but i t does not work... it show message like   
test.jmx file could not found in /tmp/test.jmx..

should i configure path ? or Add jmx file into container ?

Thanks,

**Comment by chiabre** [comment]
I guess - not sure - that you can not use native Windows path formats for
your host directory. Instead, you need to convert your path into a
quasi-Linux format.


try

docker run --rm --name jmeter -i  -v //c/jmetertest:/tmp -p
9270:9270 chiabre/jmeter_prom_exporter -t test.jmx


Il giorno mer 7 apr 2021 alle ore 19:40 dnbhatt1991 <
***@***.***> ha scritto:

**Comment by dnbhatt1991** [comment]
hello , 
i have found solution  just need to add mount path  :) 

docker run --rm --name jmeter -i  -v //c/jmetertest:/tmp -p
9270:9270 chiabre/jmeter_prom_exporter -t  /tmp/test.jmx.

**Comment by dharanyacogni** [comment]
Hi Chiabre,

My Jmx file is located in the below D:\JMETER\apachejmeter\bin\Traveldemo and im running the below command 
docker run --rm --name jmeter -i -v //d/apachejmeter/bin/Traveldemo:/tmp -p 9270:9270 chiabre/jmeter_prom_exporter -t travelomatix.jmx

but i'm getting error as below,

An error occurred: The file /opt/apache-jmeter-5.4.1/travelomatix.jmx doesn't exist or can't be opened

<img width="747" alt="image" src="https://user-images.githubusercontent.com/127280746/227934790-5b609f09-b348-4c53-b546-125ca35f0220.png">

**Comment by chiabre** [comment]
Hi,
the folder containing the test plan (jmx file) has to be mounted into the
tmp folder (JMeter workingdir).

Your startup command seems correct. Could you please try to pull the latest
docker image (I updated it today) and try again?

chiabre
